version: '3.5'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_shop1
      OSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash entrypoint.sh
    ports:
      - "8000:8000"
    environment:
        SECRET_KEY: django-insecure-d+o8mo&qmak6^d=05*-jf3^fhgx&$m4mgr6tub5=(dk2m3x8l^
        DEBUG: True
        POSTGRES_HOST: my_shop1
        POSTGRES_PORT: 5432
        POSTGRES_NAME: my_shop1
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    depends_on:
        - db

volumes:
  postgres_data:



